version: '3'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - "3456:80"
  db:
    image: mysql:8.3
    environment:
      - MYSQL_DATABASE=projekcik
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"


       